all: stat myls mytail myfind

stat: stat.c
	gcc -o stat.out stat.c -Wall

myls: myls.c
	gcc -o myls.out myls.c -Wall

mytail: mytail.c
	gcc -o mytail.out mytail.c -Wall

myfind: myfind.c
	gcc -o myfind.out myfind.c -Wall
