all: 1 2 3 4 5 6 7 8

clean:
	rm -f 1.out 2.out 3.out 4.out 5.out 6.out 7.out 8.out

1: 1.c
	gcc -o 1.out 1.c -Wall

2: 2.c
	gcc -o 2.out 2.c -Wall

3: 3.c
	gcc -o 3.out 3.c -Wall

4: 4.c
	gcc -o 4.out 4.c -Wall

5: 5.c
	gcc -o 5.out 5.c -Wall

6: 6.c
	gcc -o 6.out 6.c -Wall

7: 7.c
	gcc -o 7.out 7.c -Wall

8: 8.c
	gcc -o 8.out 8.c -Wall
